pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
                echo "success"
            }
        }
        stage('Build') {
            steps {
                dir ('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                   sh  'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build & Push') {
            environment {
                DOCKER_IMAGE = "krishna075/ultimate-cicd:${BUILD_NUMBER}"
            }
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app'){
                    script {
                        def dockerImage = docker.build("${DOCKER_IMAGE}")
                        echo " Docker image is ${DOCKER_IMAGE}"
                        docker.withRegistry('https://index.docker.io/v1/', "docker-cred"){
                        dockerImage.push()    
                        }
                }
            }
        }
        }
        
        stage('update deployment file') {
            environment {
                GIT_REPO_NAME = 'Jenkins-Zero-To-Hero'
                GIT_USER_NAME = 'GOPALAKRISHNA-5143'
            }

            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    git config user.email "krishna075143@gmail.com"
                    git config user.name "GOPALAKRISHNA-5143"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
                    git commit -m "update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                }
            }
        }
            
    }
}
