pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
                echo "success"
            }
        }
        stage('Build') {
            steps {
                dir ('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                   sh  'mvn clean package -DskipTests'
                }
            }
        }
        stage ('unit test') {
            steps {
                dir ('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('trivy file system scan') {
            steps {
                dir ('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    sh '''
                        trivy fs --exit-code 1 \
                        --severity HIGH,CRITICAL \
                        --format table \
                        --output trivy-fs-report.txt . '''
                }
            }
            
        }        
        stage('Build & Push') {
            environment {
                DOCKER_IMAGE = "krishna075/ultimate-cicd:${BUILD_NUMBER}"
            }
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app'){
                    script {
                        def dockerImage = docker.build("${DOCKER_IMAGE}")
                        echo " Docker image is ${DOCKER_IMAGE}"
                        docker.withRegistry('https://index.docker.io/v1/', "docker-cred"){
                        dockerImage.push()    
                        }
                }
            }
        }
        }
            
    }
}
