pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
                echo "success"
            }
        }
        stage('Build') {
            steps {
                dir ('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                   sh  'mvn clean package -DskipTests'
                }
            }
        }
        stage('static code analysis') {
            environment {
                SONAR_URL = "http://18.234.219.204:9000"
            }
            steps {
                withCredentials([string(credentialsId:'sonarqube', variable: 'SONAR_AUTH_TOKEN')]){
                    dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                        sh 'mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                    }
                }
            }
        }
        stage('Build & Push') {
            environment {
                DOCKER_IMAGE = "krishna075/ultimate-ci-cd/${BUILD_NUMBER}"
            }
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app'){
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}", 'Dockerfile')
                        echo " Docker image is ${DOCKER_IMAGE}"
                    }
                }
            }
        }
    }            
}
