pipeline {
    agent any
    env {
        x = 'Devops'
    }
    stages {
        stage ('stage1') {
            steps {
                echo 'Hello world this is first pipeline project'
                echo "This course is for ${x}"
            }
        }
    }
}
