pipeline {
    agent any
    environment {
        x = 'Devops'
    }
    stages {
        stage ('stage1') {
            steps {
                echo 'Hello world this is first pipeline project'
                echo "This course is for ${x}"
                echo "Build id - ${env.BUILD_ID}, Build number- ${env.BUILD_NUMBER}, jenkins url - ${JENKINS_URL}"
            }
        }
    }
}
